### ISSUE TITLE
Universal Coins Bug

### ISSUE THREAD

**Issue by GabrielFrohlich** [notabadminer/UniversalCoins#18]
Caused by: java.lang.NullPointerException
	at universalcoins.item.ItemUCCard.func_180614_a(ItemUCCard.java:50) ~[ItemUCCard.class:1.12.2-0.9.1]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:837) ~[ForgeHooks.class:9e0b1b1]
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:241) ~[aip.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:590) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:1139) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_271]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_271]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more

**Comment by notabadminer** [comment]
should have been fixed with commit 87067f1. Reopen if this happens with the next release
